Repository batterydied/Aquatica, pull requests merged in 2024-12, with the labels that each got.

#95 Fix marketplace page styling #94
  frontend/main/components/MarketplacePage/MarketplacePage.css
Labels: enhancement

#111 Integrate Marketplace Page with Backend #61 Fix bugs to allow data to…
  frontend/main/components/MarketplacePage/MarketplacePage.js
  frontend/main/services/ProductService.js
  frontend/main/services/Service.js
Labels: fixed bug, Await Review

#132 Main2
  backend/database.sqlite
  frontend/index.html
  frontend/main/components/NavigationMenu/NavigationMenu.js
Labels: Await Review

#142 Fix average rating calculation #140 merge changes from old branch
  frontend/main/components/MarketplacePage/MarketplacePage.js
Labels: fixed bug

#139 Issue #118 add marketplace comments
  frontend/main/components/MarketplacePage/MarketplacePage.js
Labels: documentation

#147 Update Product Page Functionality to Include Quantity and Product Type in Cart
  backend/controllers/ProductController.js
  backend/database.sqlite
  backend/models/ProductModel.js
  frontend/main/app/AppController.js
  frontend/main/components/NavigationMenu/NavigationMenu.css
  frontend/main/components/NavigationMenu/NavigationMenu.js
  frontend/main/components/ProductPage/ProductPage.css
  frontend/main/components/ProductPage/ProductPage.js
  frontend/main/components/ProductPage/events.js
Labels: New feature

#126 Issue profilepage backend
  backend/controllers/ProfileController.js
  backend/models/ProfileModel.js
  backend/routes/ProfileRoutes.js
  frontend/main/components/ProfilePage/ProfilePage.js
Labels: bug

#148 Issue #143 cart checkout bugs
  backend/controllers/CartController.js
  backend/controllers/OrderController.js
  backend/database.sqlite
  backend/models/CartModel.js
  backend/models/OrderModel.js
  backend/routes/OrderRoutes.js
  backend/server.js
  frontend/main/app/AppController.js
  frontend/main/components/ProductPage/ProductPage.js
  frontend/main/components/ProductPage/events.js
  frontend/main/components/SecureCheckout/SecureCheckout.js
  frontend/main/components/VirtualCart/VirtualCart.css
  frontend/main/components/VirtualCart/VirtualCart.js
Labels: Await Review

#163 (6) Closing Issue #72 user model
  backend/models/UserModel.js
Labels: documentation

#165 (1) Merge this first to avoid merge conflict
  backend/controllers/AuthController.js
  backend/middleware/AuthMiddleware.js
  backend/middleware/RoleMiddleware.js
  backend/models/UserModel.js
  backend/routes/AuthRoutes.js
  frontend/main/components/AuthPage/AuthPage.css
  frontend/main/components/AuthPage/AuthPage.js
  frontend/main/components/NavigationMenu/NavigationMenu.css
  frontend/main/components/NavigationMenu/NavigationMenu.js
Labels: enhancement

#178 Winifred progress report #174 Update progress report
  team/reports/winifred-nauda.md
Labels: documentation

#177 Seller product quantity #172 add field to change quantity and validation
  frontend/main/components/SellerProductPage/SellerProductPage.js
Labels: Await Review
